name: CI Workflow

on:
  push:
    branches: [main]
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: barber-shop
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:latest
        ports:
          - "6379:6379"
        volumes:
          - redis-data:/data
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -u root -p12345678 -e "SHOW DATABASES;"; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Verify database
        run: |
          mysql -h 127.0.0.1 -u root -p12345678 -e "SHOW DATABASES;"


      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Copy envs
        run: cp .env.ci .env

      - name: Start application
        run: npm run start:dev &

      - name: Wait for application to be ready
        run: sleep 10 # Ajuste o tempo de espera conforme necessário

      - name: Download OpenAPI YAML
        run: curl -o openapi.yaml http://localhost:3000/OAS/yaml

      - name: Verify downloaded file
        run: cat openapi.yaml

      - name: Commit OpenAPI YAML
        run: | 
            git checkout fetch all
            git checkout swagguer-docs
            git pull
            git commit -m "docs: update docs"
            git push --force
